all: test1 test2 test4

test1: test1.c question1.c
	gcc -Wall -std=c99 -o test1 test1.c question1.c

test2: test2.c question2.c
	gcc -Wall -std=c99 -o test2 test2.c question2.c

test4: test4.c question4.c
	gcc -Wall -std=c99 -o test4 test4.c question4.c

clean:
	rm -f test1 test2 test4
